#+title: Lab2
#+PROPERTY: header-args :results drawer

Welcome to Lab2 of *Leveraging Kubernetes for Drupal: A Beginner's Laboratory*

[[org:../repos/labs/DrupalDay2024/lab1.org][Lab1 is a pre-requirement before starting Lab2]]


* Software

https://kind.sigs.k8s.io/docs/user/quick-start/#installing-from-release-binaries

https://minikube.sigs.k8s.io/docs/start/?arch=%2Flinux%2Fx86-64%2Fstable%2Fbinary+download


* Understanding the Kubernetes Cluster Setup in Lab1

The use of =--servers 1= and =--agents 2= flags in the =k3d cluster create= command specifies the architecture of the Kubernetes cluster being created with k3d. Below is a detailed explanation of what each flag signifies and why such a configuration might be chosen.

** --servers 1
   This flag instructs k3d to create the cluster with 1 server node. In the context of Kubernetes:
   - A server node acts as a master node.
   - It is responsible for managing the cluster and scheduling applications to run on agent nodes.
   - A cluster requires at least one server node to function, but more can be added for high availability.

** --agents 2
   By setting this flag, the cluster will include 2 agent nodes. In Kubernetes terms:
   - Agent nodes, or worker nodes, are where applications (containers/pods) are actually executed.
   - Having multiple agent nodes allows for the distribution of applications across more than one node, improving performance and reliability.

** Accessing nodes
   A particular node can be accessed by attaching another pod running an image:

   #+begin_src bash
   kubectl debug node/k3d-drupal-cluster-agent-0 -it --image=ubuntu
   #+end_src

** Why Use This Configuration?

*** Load Distribution
    - Having multiple agent nodes allows applications to be spread out across nodes, enhancing performance and fault tolerance.

*** Resource Allocation
    - More nodes mean more compute resources (CPU, memory) are available for applications, accommodating more demanding workloads or multiple applications.

*** Learning and Experimentation
    - A multi-node setup is beneficial for understanding how Kubernetes manages resources and schedules workloads, offering a closer representation of a production environment compared to a single-node setup.

*** Availability
    - While this minimal setup doesn’t achieve full high availability (since there's only one server node), it introduces the concept. In production, multiple server nodes are recommended to ensure operational continuity in case of a node failure.

Therefore, the =--servers 1 --agents 2= configuration creates a small, but more realistic, multi-node Kubernetes cluster.

* Install kind and spin up a different cluster with Drupal

** Intsall kind

   1. Download and install the latest version of kind.
      #+BEGIN_SRC bash
      [ $(uname -m) = x86_64 ] && curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.24.0/kind-linux-amd64
      chmod +x ./kind
      sudo mv ./kind /usr/local/bin/kind
      #+END_SRC
   2. Verify the installation.
      #+BEGIN_SRC shell
      kind version
      #+END_SRC

      #+RESULTS:
      :results:
      kind v0.24.0 go1.22.6 linux/amd64
      :end:

** Create a new cluster

   1. Create a multi-node Kubernetes cluster named =drupal-cluster= for development and testing.
      #+BEGIN_SRC bash
      kind create cluster --config kind-lab2.yaml
      #+END_SRC
   2. Configure kubectl to use the new cluster.
      #+BEGIN_SRC bash
      kubectl config use-context kind-kind
      #+END_SRC

** Install Drupal

   1. Deploy Drupal and MariaDB. This will use the same helm charts from Lab 1.
      #+BEGIN_SRC bash
      helm install my-drupal bitnami/drupal -f values.yaml
      #+END_SRC

* Increase the number of replicas of the drupal deployment to 2


** Method 1: Using kubectl scale

   This command tells Kubernetes to adjust the my-drupal deployment to have 2 replicas:

   #+begin_src bash
   kubectl scale deployment my-drupal --replicas=2 -n default
   #+end_src


** Method 2: Editing the Deployment

   Alternatively, you can manually edit the deployment to change the number of replicas.

   #+begin_src bash
   kubectl edit deployment my-drupal -n default
   #+end_src

   This command opens the deployment's YAML in your default text editor. Find the replicas field under spec and change its value from 1 to 2. If the replicas field is not present, you can add it under spec:

   #+begin_src yaml
   spec:
     replicas: 2
   #+end_src

   After saving your changes and exiting the editor, Kubernetes applies the update the deployment, scaling it to 2 replicas.


** Method 3: Installing with a values.yaml file


   1. Download and modify the default values file:
      #+BEGIN_SRC bash
      curl -s https://raw.githubusercontent.com/bitnami/charts/refs/heads/main/bitnami/drupal/values.yaml
      #+END_SRC

   2. Start the my-drupal deployment with the replicas changes in the values file
      #+BEGIN_SRC bash
      helm install my-drupal bitnami/drupal -f values.yaml
      #+END_SRC


** Verifying the Change

   After scaling the deployment, you can verify that the number of replicas has been updated by listing the pods:

   #+begin_src sh
   kubectl get pods -n default -l app.kubernetes.io/name=drupal
   #+end_src

   #+RESULTS:
   : NAME                         READY   STATUS    RESTARTS   AGE
   : my-drupal-7df65485cc-9hxpz   1/1     Running   0          45s
   : my-drupal-7df65485cc-ww5p5   1/1     Running   0          14m


   This command lists all pods with the label app.kubernetes.io/name=drupal, which should include your my-drupal pods.
   You should see 2 pods running if the scaling operation was successful.
   Currently there seems to be a bug with the apache container failing with


* Adding Persistent Storage for Drupal Using Helm and a manual PVC

#+PROPERTY: header-args :results pp :var MYHOSTPATH='/home/ricardo/tmp/lab1'


** Step 1: Prepare Shared Directory

 1. Create a directory on your host system to store Drupal files and database persistently.

   #+BEGIN_SRC bash
   mkdir -p ${MYHOSTPATH}/drupal1
   cd ${MYHOSTPATH}
   chmod o+wx ${MYHOSTPATH}/*
   ls -larth
   pwd
   #+END_SRC

   #+RESULTS:
   : total 88K
   : drwxrwxr-x 24 ricardo ricardo  68K out  5 22:46 ..
   : drwxrwxrwx  5 ricardo ricardo 4,0K out  7 00:06 .
   : drwxrwxrwx  2 ricardo root    4,0K out  7 00:18 drupal1


   Replace $MYHOSTPATH with the actual path where you want to store your data.

 2. Start the cluster and add the local-pvc

   #+BEGIN_SRC bash
   kind create cluster --config kind-config.yaml

   #minikube start --driver=kvm2 && minikube mount /home/ricardo/tmp/lab1:/lab1
   #k3d cluster create drupal-cluster --servers 1 --agents 2 --volume $MYHOSTPATH:/lab1
   #kubectl apply -f local-pvc-db-drupal.yaml
   #+END_SRC

   WARNING: Both applications have some issues mounting external volumes

** Step 2: Install Drupal with Helm using a PVC

 1. Create a PersistentVolumeClaim (PVC)

   #+BEGIN_SRC bash

   echo '
apiVersion: v1
kind: PersistentVolume
metadata:
  name: drupal1-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/lab1/drupal1"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drupal1-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
   ' | kubectl apply -f -
   #+END_SRC

   #+RESULTS:
   : persistentvolume/drupal1-pv-volume created
   : persistentvolumeclaim/drupal1-pv-claim created

 2. Install the Drupal chart with the =PVC= persistence setting.

   #+BEGIN_SRC sh
   helm install my-drupal bitnami/drupal \
     --set persistence.enabled=true,persistence.existingClaim=drupal1-pv-claim,mariadb.primary.persistence.existingClaim=drupal1-pv-claim
   #+END_SRC

   #+RESULTS:
   #+begin_example
   NAME: my-drupal2
   LAST DEPLOYED: Sun Oct  6 23:38:09 2024
   NAMESPACE: default
   STATUS: deployed
   REVISION: 1
   TEST SUITE: None
   NOTES:
   CHART NAME: drupal
   CHART VERSION: 20.0.9
   APP VERSION: 11.0.5** Please be patient while the chart is being deployed **

   1. Get the Drupal URL:

     NOTE: It may take a few minutes for the LoadBalancer IP to be available.
           Watch the status with: 'kubectl get svc --namespace default -w my-drupal2'

     export SERVICE_IP=$(kubectl get svc --namespace default my-drupal2 --template "{{ range (index .status.loadBalancer.ingress 0) }}{{ . }}{{ end }}")
     echo "Drupal URL: http://$SERVICE_IP/"

   2. Get your Drupal login credentials by running:

     echo Username: user
     echo Password: $(kubectl get secret --namespace default my-drupal2 -o jsonpath="{.data.drupal-password}" | base64 -d)

   WARNING: There are "resources" sections in the chart not set. Using "resourcesPreset" is not recommended for production. For production installations, please set the following values according to your workload needs:
     - resources
   +info https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
   #+end_example


** Notes on Using =hostPath=
  - =hostPath= is primarily suited for single-node testing and development.
  - Be aware of security implications, as =hostPath= can access almost any files on the host.
  - Data stored in =hostPath= persists across Pod restarts but is tied to the specific node. If the node is lost, so is the data, unless backups are made.
  - =hostPath= has not been thoroughly tested on Windows with supported VM drivers. For development on Windows, consider alternatives like syncing files with =docker-sync= or using Minikube's mounting features.


* Adding Persistent Storage using NFS dynamic path creation directly within PersistentVolume (PV) or PVC specifications based on deployment names

** Introduction
   This guide outlines how to achieve dynamic directory creation for each deployment in Kubernetes using an NFS server and dynamic provisioning.

** Step 1: Set Up an NFS Server
   - Install NFS on your server, which can be a Kubernetes node or any other server.
   - Configure =/etc/exports= to export your desired directory, such as =/lab1=.

     #+BEGIN_SRC sh
     sudo apt install nfs-kernel-server
     sudo mkdir -p /opt/lab1
     sudo chown nobody:nogroup /opt/lab1

     sudo nano /etc/exports
     #+END_SRC

     add line:

     /opt/lab1 172.18.0.1/16(rw,sync,no_subtree_check)

     #+BEGIN_SRC sh
     sudo exportfs -a
     sudo systemctl restart nfs-kernel-server
     showmount -e localhost
     #+END_SRC


** Step 2: Install an NFS Dynamic Provisioner
   - The NFS Subdir External Provisioner automatically creates directories within your NFS share for each PVC.
   - Install the provisioner using Helm:

     #+BEGIN_SRC sh
     helm repo add nfs-subdir-external-provisioner https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
     helm install nfs-subdir-external-provisioner nfs-subdir-external-provisioner/nfs-subdir-external-provisioner \
         --set nfs.server=<your-nfs-server-ip> \
         --set nfs.path=/opt/lab1
     #+END_SRC

   - Replace <your-nfs-server-ip> with the IP address or hostname of your NFS server.

** Step 3: Use the StorageClass for Dynamic PVCs
   - The NFS Subdir External Provisioner creates a StorageClass. PVCs using this StorageClass will have a unique directory within the NFS share.
   - Example PVC definition:

     #+BEGIN_SRC yaml
     apiVersion: v1
     kind: PersistentVolumeClaim
     metadata:
       name: dynamic-pv-claim-drupal
     spec:
       accessModes:
         - ReadWriteOnce
       storageClassName: "nfs-client" # Match the StorageClass name
       resources:
         requests:
           storage: 1Gi
     ---
     apiVersion: v1
     kind: PersistentVolumeClaim
     metadata:
       name: dynamic-pv-claim-database
     spec:
       accessModes:
         - ReadWriteOnce
       storageClassName: "nfs-client" # Adjust to your NFS StorageClass
       resources:
         requests:
           storage: 1Gi
     #+END_SRC

** Full working commands
   
   k3d does no support nfs mounts and kind has some other problems with it, therefore we use =minikube= to demonstrate nfs pvc across nodes

   #+BEGIN_SRC bash :results pp
   minikube start

   helm install nfs-subdir-external-provisioner nfs-subdir-external-provisioner/nfs-subdir-external-provisioner \
         --set nfs.server=10.10.10.108 \
         --set nfs.path=/opt/lab1


   echo '
   apiVersion: v1
   kind: PersistentVolumeClaim
   metadata:
     name: nfs-drupal-pv-claim
   spec:
     accessModes:
       - ReadWriteOnce
     storageClassName: "nfs-client"
     resources:
       requests:
         storage: 1Gi
   ' | kubectl apply -f -


   helm install nfs-drupal bitnami/drupal \
     --set image.debug=true,persistence.enabled=true,persistence.existingClaim=nfs-drupal-pv-claim,mariadb.primary.persistence.existingClaim=nfs-drupal-pv-claim
   #+END_SRC


   1. Get the Drupal URL:

     NOTE: It may take a few minutes for the LoadBalancer IP to be available.
           Watch the status with: 'kubectl get svc --namespace default -w my-drupal'

     export SERVICE_IP=$(kubectl get svc --namespace default my-drupal --template "{{ range (index .status.loadBalancer.ingress 0) }}{{ . }}{{ end }}")
     echo "Drupal URL: http://$SERVICE_IP/"

   2. Get your Drupal login credentials by running:

     echo Username: user
     echo Password: $(kubectl get secret --namespace default my-drupal -o jsonpath="{.data.drupal-password}" | base64 -d)

   WARNING: There are "resources" sections in the chart not set. Using "resourcesPreset" is not recommended for production. For production installations, please set the following values according to your workload needs:
     - resources
   +info https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
   #+end_example

   #+begin_src bash :results pp
   tree -ush -L 2 /opt/lab1/
   #+end_src

   #+RESULTS:
   #+begin_example
   [ricardo  4.0K]  /opt/lab1/
   ├── [root     4.0K]  default-dynamic-pv-claim-pvc-7e8c6909-060a-46f2-822b-d9ff35ce70b6
   │   ├── [1001     4.0K]  data
   │   ├── [1001     4.0K]  modules
   │   ├── [1001     4.0K]  profiles
   │   ├── [1001     4.0K]  sites
   │   └── [1001     4.0K]  themes
   └── [root     4.0K]  default-my-drupal-pv-claim-pvc-0524da5e-6fcf-454c-8c72-866a240a9a95
       ├── [1001     4.0K]  data
       ├── [1001     4.0K]  modules
       ├── [1001     4.0K]  profiles
       ├── [1001     4.0K]  sites
       └── [1001     4.0K]  themes

   12 directories, 0 files
   #+end_example




** Notes:
   - This setup does not directly use the deployment name for directory paths but achieves dynamic storage creation without manual PV or directory creation.
   - Ensure the NFS provisioner is correctly set up, and the NFS server allows the Kubernetes nodes to access the exported directories.
   - Adjust the PVC storageClassName to match the actual StorageClass name provided by your dynamic provisioner.


* Attributing ingress with DNS


* Using an image from DDEV
