#+title: Lab2
#+PROPERTY: header-args :results drawer

Welcome to Lab2 of *Leveraging Kubernetes for Drupal: A Beginner's Laboratory*
[[org:../repos/labs/DrupalDay2024/lab1.org][Lab1 is a pre-requirement before starting Lab2]]

* Other Software for spinning up Kubernetes clusters
https://kind.sigs.k8s.io/docs/user/quick-start/#installing-from-release-binaries
https://minikube.sigs.k8s.io/docs/start/?arch=%2Flinux%2Fx86-64%2Fstable%2Fbinary+download

* Understanding the Kubernetes Cluster Setup in Lab1

The use of =--servers 1= and =--agents 2= flags in the =k3d cluster create= command specifies the architecture
of the Kubernetes cluster being created with k3d. Below is a detailed explanation of what each flag signifies
and why such a configuration might be chosen.

** --servers 1
This flag instructs k3d to create the cluster with 1 server node. In the context of Kubernetes:
- A server node acts as a master node.
- It is responsible for managing the cluster and scheduling applications to run on agent nodes.
- A cluster requires at least one server node to function, but more can be added for high availability.

** --agents 2
By setting this flag, the cluster will include 2 agent nodes. In Kubernetes terms:
- Agent nodes, or worker nodes, are where applications (containers/pods) are actually executed.
- Having multiple agent nodes allows for the distribution of applications across more than one node, improving performance and reliability.

** Accessing nodes
A particular node can be accessed by attaching another pod running an image:
#+begin_src bash
kubectl debug node/k3d-drupal-cluster-agent-0 -it --image=ubuntu
#+end_src

** Why Use This Configuration?
*** Load Distribution
- Having multiple agent nodes allows applications to be spread out across nodes, enhancing performance and fault tolerance.
*** Resource Allocation
- More nodes mean more compute resources (CPU, memory) are available for applications, accommodating more demanding workloads or multiple applications.
*** Learning and Experimentation
- A multi-node setup is beneficial for understanding how Kubernetes manages resources and schedules workloads, offering a closer representation of a production environment compared to a single-node setup.
*** Availability
- While this minimal setup doesn’t achieve full high availability (since there's only one server node), it introduces the concept. In production, multiple server nodes are recommended to ensure operational continuity in case of a node failure.
Therefore, the =--servers 1 --agents 2= configuration creates a small, but more realistic, multi-node Kubernetes cluster.

* Use namespaces to separate Drupal sites



** Create a namespace for the Drupal deployment:

- What is a namespace?
In Kubernetes, a **namespace** partitions cluster resources for multiple users or teams,
ensuring organization and management. It offers isolation, resource quotas, and access control.
While not a strict security boundary, namespaces help logically separate resources.
They are essential for large environments, allowing efficient, organized, and controlled resource management.

#+begin_src bash
kubectl create namespace drupal
#+end_src

** Install Drupal

1. Deploy Drupal and MariaDB. This will use the same helm charts from Lab 1 but on a different namespace
#+BEGIN_SRC bash
helm install my-drupal bitnami/drupal -n drupal
#+END_SRC

Yes, you can have multiple sites with the same deployment name in different namespaces!

The previous Drupal site was deployed in the "default" namespace:

#+begin_src bash
kubectl get deployments -A
#+end_src

#+RESULTS:
: NAMESPACE     NAME                     READY   UP-TO-DATE   AVAILABLE   AGE
: default       my-drupal                1/1     1            1           2m26s
: drupal        my-drupal                5/5     5            5           10m
: kube-system   coredns                  1/1     1            1           38m
: kube-system   local-path-provisioner   1/1     1            1           38m
: kube-system   metrics-server           1/1     1            1           38m
: kube-system   traefik                  1/1     1            1           37m



* Increase the number of replicas of the drupal deployment to 2

** Method 1: Using kubectl scale
This command tells Kubernetes to adjust the my-drupal deployment to have 2 replicas:
#+begin_src bash
kubectl scale deployment my-drupal --replicas=2 -n drupal
#+end_src

** Method 2: Editing the Deployment

Alternatively, you can manually edit the deployment to change the number of replicas.
#+begin_src bash
kubectl edit deployment my-drupal -n drupal
#+end_src
This command opens the deployment's YAML in your default text editor. Find the replicas field under spec and change its value from 1 to 2. If the replicas field is not present, you can add it under spec:
#+begin_src yaml
spec:
replicas: 2
#+end_src
After saving your changes and exiting the editor, Kubernetes applies the update the deployment, scaling it to 2 replicas.

** Method 3: Installing with a values.yaml file

1. Download and modify the default values file:
#+BEGIN_SRC bash
curl -s https://raw.githubusercontent.com/bitnami/charts/refs/heads/main/bitnami/drupal/values.yaml
#+END_SRC
2. Start the my-drupal deployment with the replicas changes in the values file
#+BEGIN_SRC bash
helm install my-drupal bitnami/drupal -f values.yaml -n drupal
#+END_SRC

** Verifying the Change

After scaling the deployment, you can verify that the number of replicas has been updated by listing the pods:
#+begin_src sh
kubectl get pods -n drupal -l app.kubernetes.io/name=drupal
#+end_src
#+RESULTS:
: NAME READY STATUS RESTARTS AGE
: my-drupal-7df65485cc-9hxpz 1/1 Running 0 45s
: my-drupal-7df65485cc-ww5p5 1/1 Running 0 14m
This command lists all pods with the label app.kubernetes.io/name=drupal, which should include your my-drupal pods.

You should see 2 pods running if the scaling operation was successful.
Currently there seems to be a bug with the apache container failing with

* Auto-Scaling


1.  Modify the `values.yaml` file to include resource requests and limits for both the Drupal and MariaDB containers.
    Example:
    #+begin_src yaml
    drupal:
      resources:
        requests:
          cpu: 500m
          memory: 512Mi
        limits:
          cpu: 1000m
          memory: 1024Mi
    mariadb:
      resources:
        requests:
          cpu: 300m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi
    #+end_src

1.  Create an HPA to automatically scale the number of Drupal pods based on CPU utilization:
    #+begin_src bash
    kubectl autoscale deployment my-drupal --cpu-percent=50 --min=1 --max=5 -n drupal
    #+end_src
2.  Monitor HPA:
    #+begin_src bash
    kubectl get hpa -n drupal
    #+end_src

* Extra challenges

** CI/CD Pipeline (Basic)
1. Set up a simple CI/CD pipeline using a tool like Jenkins or GitLab CI to automate the process of building a Drupal image, pushing it to a container registry, and deploying it to the Kubernetes cluster. (Detailed steps depend on the chosen CI/CD tool).

** Configuration Management
1.  Create a ConfigMap with Drupal settings:
    #+begin_src bash
    kubectl create configmap drupal-config --from-literal=site_name="My Drupal Site" -n drupal
    #+end_src
2.  Mount the ConfigMap to the Drupal deployment.

** Effective Monitoring Strategies
1.  Deploy Prometheus and Grafana for monitoring (using Helm charts or manifests).
2.  Set up Grafana dashboards to visualize Drupal performance metrics.
3.  Implement alerting rules in Prometheus to notify administrators of critical events.

** Adding Persistent Storage for Drupal Using Helm and a manual PVC
#+PROPERTY: header-args :results pp :var MYHOSTPATH='/home/r
